### ISSUE TITLE
How to associate epubs with orgfiles?

### ISSUE THREAD

**Issue by djudjuu** [bddean/emacs-ereader#10]
Hi,

I have trouble understanding how to use annotations. 

I create a link from a highlighted region and insert into an org-file. then i write some text behind that i want to be shown as annotation in the ereader-window.
 
How do i tell the epubfile to load from the org-file?
From the info i understand that the this should be loaded from the variable "ereader-annotation-files"
, which is a list of booktitles (ereader-meta-title) and org files (path/to/orgfile?).

But how do I fill that list? the only way I know how to access it is to navigate over the help menu and then click on customize....is that intended? if so what is the  exact name for the bookname-variable?

Thanks! 
(now i go learn some more elisp)

**Comment by bddean** [comment]
Unfortunately there's no interactive way to set `ereader-annotation-files at the moment. You need to set it in your .emacs. Here's my configuration (for some books from one of my classes):
```
(setq ereader-annotation-files '(

                                 ("After Virtue: A Study in Moral Theory, Third Edition" .
                                  ("/home/ben/notes/ethics/ethics.org"))

                                 ("Discipline & Punish: The Birth of the Prison" .
                                  ("/home/ben/notes/ethics/ethics.org"))

                                 ))
```
So each book has an entry in the list. Replace the title with the value of the title from `C-h v ereader-meta-title RET` and the path with your own notes file. Text in an org file after a link appear as annotations to the
linked position.
