### ISSUE TITLE
File mode specification error

### ISSUE THREAD

**Issue by cordawyn** [bddean/emacs-ereader#12]
Hi!

Here's my small contribution to the project I like and use quite often :-)

I'm trying to open the epub file with the documentation for Idris (available from http://readthedocs.org/projects/idris/downloads/epub/latest/), but it is not "rendered" completely, perhaps due to the following error that pops up:
````
File mode specification error: (error "Invalid image type `png'")
````
(I'm not using a GUI version of emacs, if that helps).

Additionally, the rendered part ends up as a "modified" buffer. Probably it would make sense to turn off the undo history for the ereader buffer too.

**Comment by bddean** [comment]
Thanks, good catches. I'll see if I can get to these this weekend.

**Comment by bddean** [comment]
Hi cordawyn,

Sorry, just getting around to this -- I pushed a fix to disable undo but wasn't able to reproduce the png issue. Could you share a full stacktrace by running M-: `(setq debug-on-error t)` before opening the epub? Also, are you able to open png files by just navigating to them in emacs?

Ben

**Comment by bddean** [comment]
Actually, there is a partial fix to catch errors in individual pages now -- so it shouldn't stop the whole book from loading

**Comment by cordawyn** [comment]
I got the latest update from elpa -- so now I'm not getting the error message above. But neither I'm getting any errors with `debug-on-error` enabled :-)

With the latest update the book rendering seems to stop at 1/4 of the file, right before the start of "Interactive Editing" section.

I also noticed that the headers are rendered twice. Check out for example, the very first "Documentation for the Idris Language", "The Idris Tutorial" and so on.

As for PNG files, I'm pretty sure my emacs can open them, being the vanilla Debian package. However, since I'm using it via a remote (text) console, I cannot tell for sure -- I get "Cannot display image: (Display does not support images)" response.

nb: ugh... and it seems I can no longer navigate the links or chapters: `ereader-follow-link: Wrong type argument: markerp, nil`, `ereader-goto-chapter: Wrong type argument: markerp, nil`. Must be somehow related to the disabling of undo thing.

**Comment by cordawyn** [comment]
UPDATE: I got the latest version of the epub and it is now rendered entirely, without any strangeness mentioned above. I guess, this bug can be closed now. Thank you!

The headers are still duplicated though - I'll open another issue for that.
