### ISSUE TITLE
ereader mode doesn't activate

### ISSUE THREAD

**Issue by DriXse** [bddean/emacs-ereader#2]
Hi,
i'm very interested in this package (finally an real epub reader with comment !), please can you add a guide to activate it ?
after install with melpa,  i try
require  ('ereader)
(ereader-mode 1) 
but it doesn't work.

thank you

**Comment by bddean** [comment]
Does navigating to an epub file after evaluating (require 'ereader) work?

**Comment by DriXse** [comment]
Ok that's work, thanks you :)
