### ISSUE TITLE
Images shouldn't be only at the beginning of the buffer

### ISSUE THREAD

**Issue by bricewge** [bddean/emacs-ereader#3]
When an epub contain images they are all put at the beginning of the buffer before the text. They should be at their respective position through out the text as other epub readers do.

Here is an [example](http://www.gutenberg.org/ebooks/28885) of an epub with this issue.

Thanks a lot for this package I was looking for some time for a way to read books in emacs and this one is good enough to ditch the Calibre ebook reader away.

**Comment by bddean** [comment]
Fixed, but images don't always align the right way with text -- the above Alice in Wonderland text is a good example. I don't  know if that's fixable without css support.

Thanks for the feedback!

**Comment by bricewge** [comment]
Thanks you for fixing this!

The horizontal alignment of images is not an issue for me, and I don't recall any other mode that achieved this in emacs. For me the most important is to have the image in context with the paragraphs.
