### ISSUE TITLE
Installed from Melpa, still shows Zip-Archive mode

### ISSUE THREAD

**Issue by benyomin** [bddean/emacs-ereader#6]
Hi, I installed emacs-treader from Melpa then created an org-buffer.  Linked to a .epub with C-c C-l 2 different ways.  When I choose file:  the epub opens in iBooks.  when I choose file+emacs: the epub opens in emacs but is still in Zip-Archive Mode.  How do I enable ereader mode?

**Comment by bddean** [comment]
Hi!

Is this just a problem with orgmode links? When you navigate to a .epub from Emacs does it open in ereader-mode?

If not I guess try running "(require 'ereader) (require 'org-ebook)".

There was a problem storing epub links that I just fixed in 822a84c. Maybe that has something to do with it?
