### ISSUE TITLE
file mode specification error when opening

### ISSUE THREAD

**Issue by djudjuu** [bddean/emacs-ereader#9]
Hi, 
I always get this error when i try opening an epub file with C-x C-f

File mode specification error: (wrong-type-argument listp "en")

i then see an empty buffer in (Ereader View) -mode

My emacs version is 24.5.1
i am quite fresh to emacs so i am not sure, whether i did install and require it the right way.
for installation found it in the elpa-list via M-x list-packages, then hit install. 
then i required it in the .emacs

to make sure, i used this minimal .emacs below and an epub from [here](https://pressbooks.com/sample-books/)

I'd be happy for any hints, especially those saying i am wrong and just need to do x

--------------------------
```
(when (>= emacs-major-version 24)
    (require 'package)
      (add-to-list
	   'package-archives
	      '("melpa" . "http://melpa.org/packages/")
	         t)
      (package-initialize))

(require 'ereader)
```

**Comment by bddean** [comment]
Hello,

Sorry you're having trouble (and for the late reply). It looks like it's working in Emacs 25 but not 24. I'll try to push a fix tomorrow but in the meantime you might consider upgrading to 25.

Thanks,

Ben

**Comment by djudjuu** [comment]
confirmed. its just on emacs24

**Comment by bddean** [comment]
Sorry that took so long. Did that fix the problem?

At some point I will probably stop supporting emacs 24 though.
